from .gaussian import *
from .gmm import *
from .jfa import *
from .kmeans import *
from .linear import *
from .linearscoring import *
from .mlp import *
from .plda import *
from .svm import *
from .ztnorm import *
