#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
# @author: Manuel Guenther <Manuel.Guenther@idiap.ch> 
# @date: Fri Apr 20 12:04:44 CEST 2012
#
# Copyright (C) 2011-2012 Idiap Research Institute, Martigny, Switzerland
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
The GBU (Good, Bad and Ugly) database consists of parts of the MBGC-v1 image sets.
It defines three protocols, i.e., Good, Bad and Ugly for which different model and probe images are used.
The database provides two different types of protocols:

* In the original protocol (called 'gbu') models are extracted for each file. This means that there may be 
  several models for the same client.
* The new protocol (called 'multi') provides one **or more** files for each model. Hence, only one model
  per client is generated.

There are slight differences between the two protocol types:

1. The amount of models differ, and so the amount of scores does.
2. The model id differs. For 'multi' protocol, model id and client id are the same, 
   whereas for 'gbu' protocol, model id and file id are identical.
3. Only the results generated by the 'gbu' protocol are comparable to other reported results.

.. note::

  To be consistent with other Bob databases, the default protocol type is 'multi'. 
  When you want to generate results comparable to literature, 
  you **always** have to specify type='gbu' when you query the database.

.. warning::

  **Do never mix 'gbu' and 'multi' protocol types. When you are lucky, you will get an exception,
  but also other weird things might happen!**
  

The three protocols 'Good', 'Bad' and 'Ugly' are provided for both protocol types.

Additionally, there are four different training sets, called 'x1', 'x2', 'x4' and 'x8' with different
numbers of training images (the number of training identities is the same for all training sets).

The GBU protocols do only provide a 'dev' set, but no 'eval' set. The default measurement reported is the ROC curve on the 'dev' set. 
"""

def dbname():
  """Calculates my own name automatically."""
  import os
  return os.path.basename(os.path.dirname(__file__))

from .query import Database
from .commands import add_commands
